#!/usr/bin/env bash
set -euo pipefail

VM_SSH_HOST="${VM_SSH_HOST:-127.0.0.1}"
VM_SSH_PORT="${VM_SSH_PORT:-2222}"
VM_SSH_USER="${VM_SSH_USER:-root}"
CONNECT_FILE="${MACFLOW_CONNECT_FILE:-$HOME/.config/macflow/connect.env}"
PANEL_PORT="${MACFLOW_PANEL_PORT:-18080}"

usage() {
  echo "Usage: $0 [--ssh-host HOST] [--ssh-port PORT] [--ssh-user USER] [--connect-file PATH]"
  echo ""
  echo "Environment overrides:"
  echo "  VM_SSH_HOST, VM_SSH_PORT, VM_SSH_USER"
  echo "  MACFLOW_CONNECT_FILE, MACFLOW_PANEL_PORT"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ssh-host) VM_SSH_HOST="$2"; shift 2 ;;
    --ssh-port) VM_SSH_PORT="$2"; shift 2 ;;
    --ssh-user) VM_SSH_USER="$2"; shift 2 ;;
    --connect-file) CONNECT_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown arg: $1"
      usage
      exit 1
      ;;
  esac
done

SSH_OPTS=(
  -p "$VM_SSH_PORT"
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
)

status_json="$(ssh "${SSH_OPTS[@]}" "${VM_SSH_USER}@${VM_SSH_HOST}" "tailscale status --json" 2>/dev/null || true)"
if [[ -z "$status_json" ]]; then
  echo "[ERR] tailscale status empty; check VM SSH/tailscale service"
  exit 2
fi

readarray -t parsed < <(printf '%s' "$status_json" | node -e "let t='';process.stdin.on('data',d=>t+=d);process.stdin.on('end',()=>{try{const s=JSON.parse(t||'{}');const st=s.BackendState||'';const au=s.AuthURL||'';const dn=((s.Self&&s.Self.DNSName)||'').replace(/\.$/,'');console.log(st);console.log(au);console.log(dn);}catch(e){console.log('');console.log('');console.log('');}});")

state="${parsed[0]:-}"
auth_url="${parsed[1]:-}"
dns_name="${parsed[2]:-}"

if [[ "$state" != "Running" || -z "$dns_name" ]]; then
  echo "[WAIT] tailscale not ready (state=${state:-unknown})"
  if [[ -n "$auth_url" ]]; then
    echo "[ACTION] Open and finish login: $auth_url"
  fi
  exit 3
fi

mkdir -p "$(dirname "$CONNECT_FILE")"

cat >"$CONNECT_FILE" <<EOF
# MACFlow quick-connect profile (tailscale-synced)
# Generated by vm/sync-connect-from-tailscale.sh

ISTORE_PANEL_URLS=http://${dns_name}:${PANEL_PORT},http://127.0.0.1:${PANEL_PORT}
ISTORE_LUCI_URLS=http://${dns_name},http://192.168.1.1:8080
ISTORE_SSH_TARGETS=root@${dns_name}:22,root@127.0.0.1:2222

ISTORE_HOST=192.168.1.1,192.168.50.1,10.0.0.1
MACFLOW_DISCOVER_TIMEOUT=3
MACFLOW_INSECURE_TLS=0
EOF

echo "[OK] Updated $CONNECT_FILE"
echo "[OK] Tailscale DNS: $dns_name"
echo "[TIP] Verify with: bash vm/quick-connect.sh --json"
